### ISSUE TITLE
AttributeError: 'FortranType' object has no attribute 'all_boundprocs'

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#138]
Getting an odd error if two specific files are in my project (I can't post them...will try and create a simplified reproducer if I can figure out exactly what is triggering the problem, but wanted to go ahead and log this). Either file by itself is processed fine, but when they are both there, I get this error:

````python
Processing documentation comments...
Correlating information from different parts of your project...
Traceback (most recent call last):
  File "c:\anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda\Scripts\ford.exe\__main__.py", line 9, in <module>
  File "c:\anaconda\lib\site-packages\ford\__init__.py", line 349, in run
    main(proj_data,proj_docs,md)
  File "c:\anaconda\lib\site-packages\ford\__init__.py", line 311, in main
    project.correlate()
  File "c:\anaconda\lib\site-packages\ford\fortran_project.py", line 192, in correlate
    if type(container) != str: container.correlate(self)
  File "c:\anaconda\lib\site-packages\ford\sourceform.py", line 829, in correlate
    subrtn.correlate(project)
  File "c:\anaconda\lib\site-packages\ford\sourceform.py", line 825, in correlate
    if dtype in self.types: dtype.correlate(project)
  File "c:\anaconda\lib\site-packages\ford\sourceform.py", line 1445, in correlate
    for bp in self.extends.all_boundprocs:
AttributeError: 'FortranType' object has no attribute 'all_boundprocs'
````

**Comment by jacobwilliams** [comment]
Here is a reproducer. It seems to be caused by an extended type within a module subroutine:

test_module.f90:
````Fortran
    module test_module

    type,public :: test_class
        private
    end type test_class

    end module test_module
````

blah_module.f90:
````Fortran
    module blah_module

    implicit none

    contains

    subroutine blah_proc()

        use test_module, only: test_class

        implicit none

        type,extends(test_class) :: int_type
            integer :: blah = 0
        end type int_type

    end subroutine blah_proc

    end module blah_module
````

**Comment by cmacmackin** [comment]
Sorry for my delay in responding. I don't know what the cause of this is off the top of my head. It seems that, for some reason, the `all_boundprocs` attribute isn't being created for one of the derived types (presumably the descendant). I'll try to take a look at this in the next week or so.

**Comment by cmacmackin** [comment]
Turned out it was a dumb bug in how I order analysis of modules. Fixed it now.

**Comment by jacobwilliams** [comment]
Works beautifully! Thanks!!
