### ISSUE TITLE
4.2.0 crash

### ISSUE THREAD

**Issue by jacobwilliams** [cmacmackin/ford#75]
I get a crash with current `master` from [this](https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit) project, which worked in the previous release. Traceback is:

```Python
Reading file src/complex_step.f90
Reading file src/conversion_module.f90
Reading file src/ephemeris_module.f90
Reading file src/fortran_astrodynamics_toolkit.f90
Reading file src/geodesy_module.f90
Reading file src/geometry_module.f90
Reading file src/geopotential_module.f90
Reading file src/gooding_module.f90
Reading file src/iau_orientation_module.f90
Reading file src/kind_module.f90
Reading file src/lambert_module.f90
Reading file src/math_module.f90
Reading file src/minpack_module.f90
Reading file src/numbers_module.f90
Reading file src/random_module.f90
Reading file src/relative_motion_module.f90
Reading file src/time_module.f90
Reading file src/vector_module.f90

Processing documentation comments...
Correlating information from different parts of your project...

Warning: Could not substitute link [[rk_module]]. "rk_module" not found.
Creating HTML documentation...
Traceback (most recent call last):
  File "/Users/anaconda/bin/ford", line 9, in <module>
    load_entry_point('FORD==4.2.0', 'console_scripts', 'ford')()
  File "/Users/anaconda/lib/python2.7/site-packages/ford/__init__.py", line 282, in run
    main(proj_data,proj_docs,md)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/__init__.py", line 269, in main
    docs = ford.output.Documentation(proj_data,proj_docs_,project,page_tree)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/output.py", line 70, in __init__
    self.graphs.register(item)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/graphmanager.py", line 61, in register
    ford.graphs.FortranGraph.data.register(obj,type(obj))
  File "/Users/anaconda/lib/python2.7/site-packages/ford/graphs.py", line 66, in register
    if obj not in self.procedures: self.procedures[obj] = ProcNode(obj,self)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/graphs.py", line 204, in __init__
    n = gd.get_node(c,FortranSubroutine)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/graphs.py", line 88, in get_node
    self.register(obj,cls)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/graphs.py", line 66, in register
    if obj not in self.procedures: self.procedures[obj] = ProcNode(obj,self)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/graphs.py", line 187, in __init__
    super(ProcNode,self).__init__(obj)
  File "/Users/anaconda/lib/python2.7/site-packages/ford/graphs.py", line 109, in __init__
    self.ident = obj.get_dir() + '~' + obj.ident
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by jacobwilliams** [comment]
It looks like ```obj.get_dir()``` is evaluating to ```None```. Beyond that, I have no idea.

The new graph feature is awesome, btw! It will be great to see it with this project, which has a lot of dependencies.

**Comment by cmacmackin** [comment]
I've worked out why this error is happening. It's easy enough to 
prevent, but I want to make sure I've worked out all of the implications 
for producing the graphs.

On 24/08/15 11:15 PM, Jacob Williams wrote:
>
> It looks like |obj.get_dir()| is evaluating to |None|. Beyond that, I 
> have no idea.
>
> The new graph feature is awesome, btw! It will be great to see it with 
> this project, which has a lot of dependencies.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/ford/issues/75#issuecomment-134449991>.
>

-- 
Chris MacMackin
Saint Mary's University
Curriculum Vitae <http://ap.smu.ca/%7Ecmacmack/CV.pdf>

**Comment by cmacmackin** [comment]
I've fixed this and made a new release. Turns out that I was being a bit naive about circular dependencies in call-graphs. Note that if you want graphs then you will have to add `graph: true` to the project-file.
