### ISSUE TITLE
Generic binding for deferred type-bound procedure

### ISSUE THREAD

**Issue by pheibarrass** [cmacmackin/ford#79]
When an (abstract) type has a deferred type-bound procedure, that procedure cannot be added to a type-bound generic interface.  The module

    module mod
      type, abstract :: t
       contains
         procedure(if), deferred, nopass :: f
         generic :: fg => f
      end type t

      abstract interface
         subroutine if()
         end subroutine if
      end interface
    end module mod

fails with

> Processing documentation comments...
Correlating information from different parts of your project...

> Creating HTML documentation...
Traceback (most recent call last):
  File "/home/quack/local/python/bin/ford", line 9, in <module>
    load_entry_point('FORD==4.2.1', 'console_scripts', 'ford')()
  File "/home/quack/local/python/lib/python2.7/site-packages/ford/\__init__.py", line 282, in run
    main(proj_data,proj_docs,md)
  File "/home/quack/local/python/lib/python2.7/site-packages/ford/\__init__.py", line 269, in main
    docs = ford.output.Documentation(proj_data,proj_docs_,project,page_tree)
  File "/home/quack/local/python/lib/python2.7/site-packages/ford/output.py", line 109, in \__init__
    raise e
 jinja2.exceptions.UndefinedError: 'str object' has no attribute 'meta'

**Comment by cmacmackin** [comment]
Fixed in [version 4.2.2](https://github.com/cmacmackin/ford/releases/tag/v4.2.2).
