### ISSUE TITLE
Error with TBPs in include files

### ISSUE THREAD

**Issue by kergonath** [cmacmackin/ford#94]
I get an error in the following situation.
I have a file named containing a derived type definition, with one type-bound procedure (module.f90):

    $ cat module.f90
    module module
        public

        type type
        contains
            procedure :: test_included
        end type
    contains
        include 'part.inc'
    end module

The definition of said TBP is in another file (part.inc):

    $ cat part.inc
    subroutine test_included(this, x)
        class(type), intent(in) :: this
        integer, intent(in) :: x
    end subroutine

The documentation file (doc.md) is:

    $ cat doc.md
    project: test
    summary: This is a test project
    project_dir: ./
    output_dir: ./html

I use the latest version I could get using pip:

    $ ford -V
    FORD, version 4.4.0

When I try to generate the documentation, I get the following message:

    $ ford --debug doc.md
    Reading file module.f90

    Processing documentation comments...
    Correlating information from different parts of your project...

    Creating HTML documentation...
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/output.py", line 89, in __init__
        self.docs.append(TypePage(data,project,item))
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/output.py", line 184, in __init__
        self.html = self.render(data,proj,obj)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/output.py", line 305, in render
        return template.render(data,dtype=obj,project=proj)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/templates/type_page.html", line 1, in top-level template code
        {% extends "base.html" %}
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/templates/base.html", line 99, in top-level template code
        {% block body %}
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/templates/type_page.html", line 70, in block "body"
        {{ macros.bound_info(bp) }}
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/templates/macros.html", line 443, in template
        {{ proc_summary(bind) }}
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/templates/macros.html", line 378, in template
        {% if small %}<h5>{% else %}<h3>{% endif %}{{ proc_line(proc,proto=proto) }}{% if proto %}<small>Prototype</small>{% endif %}{% if small %}</h5>{% else %}</h3>{% endif %}
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ford/templates/macros.html", line 511, in template
        {% if proc.meta['deprecated'] and proc.meta['deprecated'].lower() == 'true' %}
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/environment.py", line 389, in getitem
        return obj[argument]
    UndefinedError: 'str object' has no attribute 'meta'
    Error encountered.

**Comment by cmacmackin** [comment]
At present, FORD does not handle included files (as noted [here](https://github.com/cmacmackin/ford/wiki/Limitations)). As such it couldn't match the type-bound procedure to an implementation and crashed when it tries to access some of the information about the subroutine. Adding support for included files probably wouldn't be too hard. I'd need to add a check around [line 256](https://github.com/cmacmackin/ford/blob/master/ford/reader.py#L256) and [line 111](https://github.com/cmacmackin/ford/blob/master/ford/reader.py#L111) of [reader.py](https://github.com/cmacmackin/ford/blob/master/ford/reader.py) to see if a line is an include statement and, if it is, open a reader for it and place all of the lines of that reader's output in the `pending` list. I likely won't get to this until sometime over the Christmas holidays, however.

**Comment by kergonath** [comment]
I assumed it would be something like that. I understand that include files are not supported, but I was taught to file reports when I see internal errors :)
To be fair I had a look at the sources, but I am really bad at Python so I could not really understand what was going on.
I worked around by copying a bunch of procedures from the include file to the source file. That is a bit clunky, I now have a couple of very long source files. Actually, the include files were already supposed to work around the lack of submodule support in most compilers.
Anyway, as far as I am concerned it is now working but I figured a report might still be useful. Thanks for the time you spend on FORD, it is very helpful and much appreciated.

**Comment by cmacmackin** [comment]
Another workaround is to use the precompiler's `#include` feature and give your files the extension `.F90`. FORD should be able to handle that just fine.

Don't feel bad about not understanding the source files. They are a bit of a mess and `reader.py` is particularly bad--basically I just pray that it never breaks and that no one asks for a new feature which requires me to alter its algorithm. FORD was the first major piece of software I wrote and, as such, was very much a learning experience for me in terms of good software design.

**Comment by cmacmackin** [comment]
I've added support for the include statement. A new release, with this feature, should be out within a few days.

**Comment by kergonath** [comment]
Thanks! I am away now but I will try that when I am home.
